# Site settings
title: okaitslinblog
email: okaits7534@gmail.com
description: okaitsが作ったブログです！主にPCについての記事を投稿しています！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://okaitslinblog.github.io" # the base hostname & protocol for your site
twitter_username: okaits7534
github_username:  okaitslinblog

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: RSS Feed
    link: https://okaitslinblog.github.io/feed.xml

disqus: true
disqus_shortname: 'okaitslinblog'

# Build settings
markdown: kramdown
